python prediction.py \
--dataset ./dataset/ \
--ckpt_path ./checkpoints/cityscapes_unet_SGD_randomcrop_100e_v2/ \
--results_path ./results/cityscapes_unet_SGD_randomcrop_100e_v2/ \
--epochs 99 \
--batch_size 16 \
--opt SGD \
--h 512 \
--w 1024 \
--split test \
