python train.py \
--dataset ./dataset/ \
--ckpt_path ./checkpoints/cityscapes_unet_SGD_randomcrop_100e/ \
--results_path ./results/cityscapes_unet_SGD_randomcrop_100e/ \
--network Unet \
--epochs 100 \
--n_classes 34 \
--batch_size 12 \
--h 512 \
--w 1024 \
--opt SGD \
--gpus 3
